BOOKS_SHEET_NAME = "Books"

BOOKS_HEADERS = [
    "ISBN",
    "Title",
    "Subtitle",
    "Author",
    "Editorial",
    "Synopsis",
    "Subject",
    "SubjectCode",
    "CoverURL",
]

REVIEW_SHEET_NAME = "Review"

REVIEW_HEADERS = [
    "ISBN",
    "Title",
    "Subtitle",
    "Author",
    "Editorial",
    "Source",
    "Language",
    "Subject",
    "SubjectCode",
    "SubjectType",
    "Categories",
    "CoverURL",
    "Synopsis",
    "FieldSources",
    "SourceIssueCodes",
    "EnrichmentStatus",
    "EvidenceCount",
    "EvidenceOrigins",
    "GeneratedSynopsisFlags",
    "GeneratedSynopsisText",
    "GeneratedSynopsisRaw",
    "ReasonCodes",
    "ReviewDetails",
]

REVIEW_COLUMN_WIDTHS = {
    "A": 18,
    "B": 32,
    "C": 28,
    "D": 24,
    "E": 24,
    "F": 16,
    "G": 12,
    "H": 18,
    "I": 14,
    "J": 14,
    "K": 28,
    "L": 36,
    "M": 60,
    "N": 40,
    "O": 28,
    "P": 24,
    "Q": 14,
    "R": 28,
    "S": 36,
    "T": 48,
    "U": 60,
    "V": 28,
    "W": 60,
}
